.PHONY: clean All

All:
	@echo "----------Building project:[ LinkedList - Debug ]----------"
	@cd "LinkedList" && "$(MAKE)" -f  "LinkedList.mk"
clean:
	@echo "----------Cleaning project:[ LinkedList - Debug ]----------"
	@cd "LinkedList" && "$(MAKE)" -f  "LinkedList.mk" clean
