.PHONY: clean All

All:
	@echo "----------Building project:[ BubbleSort - Debug ]----------"
	@cd "BubbleSort" && "$(MAKE)" -f  "BubbleSort.mk"
clean:
	@echo "----------Cleaning project:[ BubbleSort - Debug ]----------"
	@cd "BubbleSort" && "$(MAKE)" -f  "BubbleSort.mk" clean
